### ISSUE TITLE
Remove duplicated content in helpful-material.html

### ISSUE THREAD

**Issue by richie-south** [lingonsaft/hacktoberfest#718]

**Comment by rafagarciac** [comment]
**Ready to do !!**
I would like to know, what exactly it's a duplicated content in the helpful-material.html
Because I see a lot of links `<a href = "x"> .... </a>`

**Comment by richie-south** [comment]
@rafagarciac If you look at this image we have multiple instances of `helpful material` title and would only like to keep one of those :) 

<img width="1295" alt="screen shot 2018-10-05 at 11 18 44" src="https://user-images.githubusercontent.com/8655479/46527098-73e47d00-c890-11e8-9845-05723bd059ae.png">

**Comment by richie-south** [comment]
Closing this because its is now fixed with #720 😃

**Comment by rafagarciac** [comment]
@richie-south 
Good Job @sarahperea, but you missed a lot of **unnecessary & duplicated** code and content...
I think that I'm doing one better version and maybe we'll have to re-open the issue.
Thanks for your attention.

**Comment by richie-south** [comment]
@rafagarciac Make you changes and then notify me here :)
